### ISSUE TITLE
Integration of sharrif? (Privacy)

### ISSUE THREAD

**Issue by WulfmanGer** [Piwigo/Piwigo-Social-Buttons#4]
Hey

in Germany we have a Problem by Law with Share-Buttons (Usertracking). OK Piwigo-Social-Button has an Privacy-Option - but with this option you don't see how many likes did you have. The popular German computer magazine c't and heise online create a solution which is compatible with law AND which is viewing your Likes:

https://github.com/heiseonline/shariff (english)

There exists Solutions for some CMS ... but piwigo ... no 

Sorry for my bad english...

Regards

**Comment by mistic100** [comment]
Hello

Sorry I don't have the time to reimplement everything with a new library.

Up to you to create a new plugin.
